# Cognito
COGNITO_CLIENT_ID: !Ref UserPoolClient
COGNITO_CLIENT_SECRET: !GetAtt UserPoolClient.ClientSecret
COGNITO_POOL_ID: !Ref UserPool

# Database
MAIN_TABLE_NAME: !Ref MainTable

# Buckets
MEALS_BUCKET: !Ref MealsBucket

# CDN
MEALS_CDN_DOMAIN_NAME: !GetAtt MealsBucketCDN.DomainName

# # CDN
# MEALS_CDN_DOMAIN_NAME: !If
#   - ShouldSetupMealsCDNCustomDomain
#   - ${env:MEALS_CDN_DOMAIN_NAME, ''}
#   - !GetAtt MealsBucketCDN.DomainName

DLQ_ALARM_EMAIL: daniel7oficial@gmail.com

# Queues
MEALS_QUEUE_URL: !Ref MealsQueue

# External services
OPENAI_API_KEY: ${env:OPENAI_API_KEY}
